// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc-Vh-sjCwVsVix-amJrGPrw-FdLFMD1o',
    appId: '1:859347064676:android:db8f9032b6955340668c71',
    messagingSenderId: '859347064676',
    projectId: 'flutter-reddit-clone-9670d',
    storageBucket: 'flutter-reddit-clone-9670d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvawxMuvMAmPgzOBXrQyzI5fvmC-B8fj4',
    appId: '1:859347064676:ios:5820b8b13f51bea0668c71',
    messagingSenderId: '859347064676',
    projectId: 'flutter-reddit-clone-9670d',
    storageBucket: 'flutter-reddit-clone-9670d.appspot.com',
    iosBundleId: 'com.example.flutterRedditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvawxMuvMAmPgzOBXrQyzI5fvmC-B8fj4',
    appId: '1:859347064676:ios:e85c8ab2d66c1914668c71',
    messagingSenderId: '859347064676',
    projectId: 'flutter-reddit-clone-9670d',
    storageBucket: 'flutter-reddit-clone-9670d.appspot.com',
    iosBundleId: 'com.example.flutterRedditClone.RunnerTests',
  );
}
